plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

group = 'com.ufscar.formularoute'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'io.github.mkpaz:atlantafx-base:2.0.1'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // ---------- Testes ----------
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.assertj:assertj-core'
    testRuntimeOnly 'com.h2database:h2'
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

javafx {
    version = '20.0.2'
    modules = [
            'javafx.base',
            'javafx.graphics',
            'javafx.controls',
            'javafx.fxml'
    ]
}

application {
    mainClass = 'com.ufscar.formularoute.Main'
}

bootJar {
    mainClass = 'com.ufscar.formularoute.Main'
    archiveFileName = 'app.jar'
}

// Impede a geração do "-plain.jar", que faria o Dockerfile
// encontrar dois arquivos ao copiar build/libs/*.jar
jar {
    enabled = false
}

test {
    useJUnitPlatform()
    systemProperty 'file.encoding', 'UTF-8'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
